#!/usr/bin/env bash
set -euo pipefail
REPO="/home/rossg/src/crossplane-providers"

# Ensure the directory exists for per‑provider markdown pages
mkdir -p "$REPO/docs/providers"

# ---- OTLP per provider ----
for d in "$REPO"/provider-*; do
  [[ -d $d ]] || continue
  name=$(basename "$d")
  trc="$d/internal/tracing/tracing.go"
  if grep -q "otlptrace\.New\|otlptracegrpc" "$trc" 2>/dev/null; then
    otp=2
  else
    otp=0
  fi
  echo "$name OTLP=$otp"
done

# ---- Retry-After per provider ----
for d in "$REPO"/provider-*; do
  [[ -d $d ]] || continue
  name=$(basename "$d")
  if grep -rn 'resp\.Header\.Get("Retry-After")' "$d"/internal/clients/*.go 2>/dev/null; then
    rat=2
  else
    rat=0
  fi
  echo "$name Retry=$rat"
done

# ---- EventRecorder per provider ----
for d in "$REPO"/provider-*; do
  [[ -d $d ]] || continue
  name=$(basename "$d")
  if grep -rn "event\.NewAPIRecorder" "$d"/internal/controller/**/*.go 2>/dev/null; then
    ev=2
  else
    ev=0
  fi
  echo "$name Event=$ev"
done
# ---------------------------------------------------------------------------
# Write per‑provider markdown pages (used by the GitHub‑Pages site)
# ---------------------------------------------------------------------------
for d in "$REPO"/provider-*; do
  [[ -d "$d" ]] || continue
  name=$(basename "$d")
  out="docs/providers/${name}.md"

  # OTLP
  otp=0; trc="$d/internal/tracing/tracing.go"
  if grep -q "otlptrace\.New\|otlptracegrpc" "$trc" 2>/dev/null; then otp=2; fi
  otp_str=$([ "$otp" -ge 1 ] && echo "✅" || echo "❌")

  # Retry‑After
  rat=0; if grep -rn 'resp\.Header\.Get("Retry-After")' "$d"/internal/clients/*.go 2>/dev/null; then rat=2; fi
  rat_str=$([ "$rat" -ge 1 ] && echo "✅" || echo "❌")

  # v2 EventRecorder
  ev=0; if grep -rn "event\.NewAPIRecorder" "$d"/internal/controller/**/*.go 2>/dev/null; then ev=2; fi
  ev_str=$([ "$ev" -ge 1 ] && echo "✅" || echo "❌")

  # API‑covered % (client‑method lines ÷ 25 × 100)
  cnt=$(grep -rh "client\.\|http\.Do\|cli\." "$d"/internal/clients/*.go 2>/dev/null | grep -v "^\s*//" | wc -l)
  pct=$(( 100 * cnt / 25 ))

  cat > "$out" <<EOF
# provider-${name} – Compliance & API coverage

**Generated by `score-providers.sh`** (heuristic checks only).

| Check | Result |
|-------|--------|
| **OTLP tracing** | ${otp_str} |
| **Retry‑After header** | ${rat_str} |
| **v2 EventRecorder** | ${ev_str} |
| **API‑covered %** | **${pct} %** |

*See the repo‑wide summary in [compliance-summary.md](../compliance-summary.md).*

EOF
done
