baseURL = 'https://rossigee.github.io/crossplane-providers/'
title = 'Crossplane Providers'
publishDir = 'public'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = 'tags'
  category = 'categories'
